-- Tabla de confirmaciones para la invitación digital
create table confirmaciones (
  id                       bigint generated by default as identity primary key,
  nombre                   text        not null,
  tipo                     text        not null check (tipo in ('familia', 'amigo')),
  asiste                   boolean     not null default true,
  cantidad_personas        int         default 1,
  "nombres_acompañantes"   text,
  transporte               boolean     not null default false,
  created_at               timestamptz not null default now()
);

-- Índice para consultas por tipo
create index on confirmaciones (tipo);

-- Row Level Security: habilitar y permitir INSERT público (anon)
alter table confirmaciones enable row level security;

create policy "Allow public insert"
  on confirmaciones
  for insert
  to anon
  with check (true);

-- Solo el service_role puede leer (para el dashboard del admin)
create policy "Allow service_role select"
  on confirmaciones
  for select
  to service_role
  using (true);
